/** 邻里课堂安全协作的领域事件类型与聚合类型常量。 */

export const EVENT_TYPES = Object.freeze({
  // 基线已有的事件
  ENROLLMENT_CONFIRMED: "ENROLLMENT_CONFIRMED",
  STAFF_CLEARED: "STAFF_CLEARED",
  SESSION_REASSIGNED: "SESSION_REASSIGNED",
  PICKUP_CHANGED: "PICKUP_CHANGED",
  CASE_ESCALATED: "CASE_ESCALATED",
  // 接送点与课程场次
  SITE_REGISTERED: "SITE_REGISTERED",
  SESSION_FROZEN: "SESSION_FROZEN",
  SESSION_CLOSED: "SESSION_CLOSED",
  // 分别版本化的四类保障文书
  GUARDIANSHIP_RECORDED: "GUARDIANSHIP_RECORDED",
  DELEGATION_RECORDED: "DELEGATION_RECORDED",
  DELEGATE_WITHDRAWN: "DELEGATE_WITHDRAWN",
  NO_RELEASE_ISSUED: "NO_RELEASE_ISSUED",
  NO_RELEASE_LIFTED: "NO_RELEASE_LIFTED",
  EMERGENCY_CONTACTS_RECORDED: "EMERGENCY_CONTACTS_RECORDED",
  // 监护人临时变更的二次核验
  TEMP_CHANGE_VERIFIED: "TEMP_CHANGE_VERIFIED",
  TEMP_CHANGE_REJECTED: "TEMP_CHANGE_REJECTED",
  TEMP_CHANGE_EXPIRED: "TEMP_CHANGE_EXPIRED",
  // 签到、交付与异常冻结
  CHILD_CHECKED_IN: "CHILD_CHECKED_IN",
  CHILD_CHECKED_OUT: "CHILD_CHECKED_OUT",
  PICKUP_REFUSED: "PICKUP_REFUSED",
  DELIVERY_FROZEN: "DELIVERY_FROZEN",
  DELIVERY_UNFROZEN: "DELIVERY_UNFROZEN",
  RECORD_REVISION_VERIFIED: "RECORD_REVISION_VERIFIED",
  RECORD_REVISION_REJECTED: "RECORD_REVISION_REJECTED",
  // 跨点调班
  TRANSFER_REQUESTED: "TRANSFER_REQUESTED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",
  TRANSFER_COMPLETED: "TRANSFER_COMPLETED",
  // 通知与确认
  NOTIFICATION_SENT: "NOTIFICATION_SENT",
  NOTIFICATION_ACKNOWLEDGED: "NOTIFICATION_ACKNOWLEDGED",
});

export const AGGREGATES = Object.freeze({
  CHILD: "child_enrollment",
  SITE: "site",
  SESSION: "site_session",
  STAFF: "staff_assignment",
  POLICY: "pickup_policy",
  TRANSFER: "transfer",
  NOTIFICATION: "notification",
  CASE: "safeguarding_case",
});

export const EVENT_TYPE_LIST = Object.freeze(Object.values(EVENT_TYPES));
export const AGGREGATE_LIST = Object.freeze(Object.values(AGGREGATES));
